// Bake a user's app identity into the shell source before `native build`.
// Reads inputs from env (set by build-app.yml workflow_dispatch), then:
//   - rewrites src/app_config.zig with the deployed URL + app name (compiled in)
//   - patches app.zon: unique .id + .display_name
//   - downloads the app's icon over assets/icon.png (native package derives the
//     platform icon set from it, so installers get the user's icon)
// Cross-platform (plain Node 22, global fetch) so it runs identically on the
// macOS / Linux / Windows runners.
import { readFile, writeFile } from "node:fs/promises";

const APP_URL = (process.env.APP_URL || "").trim();
const APP_NAME = (process.env.APP_NAME || "PiPilot").trim();
const APP_SLUG = (process.env.APP_SLUG || "").trim();
const ICON_URL = (process.env.ICON_URL || "").trim();

// --- validate + sanitize -------------------------------------------------
if (!/^https:\/\/[a-z0-9.-]+\.pipilot\.dev(\/.*)?$/i.test(APP_URL)) {
  console.error(`bake: refusing non-pipilot.dev URL: ${JSON.stringify(APP_URL)}`);
  process.exit(1);
}
// zig/zon string literals accept JSON's \\ and \" escapes and literal UTF-8, but
// NOT JSON's \uXXXX control-char form — strip control chars (and DEL) first.
const stripCtrl = (s) => String(s).replace(/[\x00-\x1f\x7f]/g, " ");
const zlit = (s) => JSON.stringify(stripCtrl(s));
const slug =
  (APP_SLUG || APP_NAME).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "").slice(0, 40) || "app";
const bundleId = `dev.pipilot.app.${slug}`;
const displayName = stripCtrl(APP_NAME).slice(0, 60);

// The shell loads this URL; the pp_desktop marker tells desktop-auth.js it's
// running in the shell (so OAuth routes through the system browser).
const markedUrl = APP_URL + (APP_URL.includes("?") ? "&" : "?") + "pp_desktop=1";

// --- src/app_config.zig --------------------------------------------------
await writeFile(
  "src/app_config.zig",
  `// Generated by ci/bake.mjs for a per-app installer build. Do not edit.\n` +
    `pub const frontend_url = ${zlit(markedUrl)};\n` +
    `pub const app_name = ${zlit(displayName)};\n`,
);

// --- app.zon: unique id + display name -----------------------------------
let zon = await readFile("app.zon", "utf8");
zon = zon.replace(/\.id\s*=\s*"[^"]*"/, `.id = ${zlit(bundleId)}`);
zon = zon.replace(/\.display_name\s*=\s*"[^"]*"/, `.display_name = ${zlit(displayName)}`);
await writeFile("app.zon", zon);

// --- icon (best-effort) --------------------------------------------------
if (ICON_URL && /^https:\/\//i.test(ICON_URL)) {
  try {
    const r = await fetch(ICON_URL, { redirect: "follow" });
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    const buf = Buffer.from(await r.arrayBuffer());
    // Guard against tiny/error bodies; keep the baked default if the icon is bad.
    if (buf.length > 512) {
      await writeFile("assets/icon.png", buf);
      console.log(`bake: icon set from ${ICON_URL} (${buf.length} bytes)`);
    } else {
      console.log(`bake: icon too small (${buf.length}b), keeping default`);
    }
  } catch (e) {
    console.log(`bake: icon fetch failed (${e.message}), keeping default`);
  }
}

console.log(`bake: url=${APP_URL} name=${JSON.stringify(displayName)} id=${bundleId} slug=${slug}`);
